name: dart_fundamentos
description: Projeto referente ao curso dart fundamentos da academia do flutter.
version: 1.0.0+1
homepage: https://academiadoflutter.com.br

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  http: ^0.13.5
  mysql1: ^0.20.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

